Mappings:
  RegionAMIMap:
    eu-west-2:
      AMI: ami-00a1270ce1e007c27
    eu-west-1:
      AMI: ami-0ce71448843cb18a1

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: 
        !FindInMap [ RegionAMIMap, !Ref AWS::Region, AMI ]
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: "Name"
          Value: "Instance test"
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  EC2Instane:
    Description: Instance ID
    Value: !Ref EC2Instance
  SecurityGroup:
    Description: Security Group ID
    Value: !GetAtt SecurityGroup.GroupId
  VPC:
    Description: VPC ID
    Value: !GetAtt SecurityGroup.VpcId