# V02 Template, with portability & reuse
Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S, M, L)
Mappings:
  RegionMap:
    eu-north-1:
      "AMALINUX": "ami-1b2fa465"
    ap-south-1:
      "AMALINUX": "ami-0cb0e70f44e1a4bb5"
    eu-west-3:
      "AMALINUX": "ami-03b4b78aae82b30f1"
    eu-west-2:
      "AMALINUX": "ami-00a1270ce1e007c27"
    eu-west-1:
      "AMALINUX": "ami-0ce71448843cb18a1"
    ap-northeast-3:
      "AMALINUX": "ami-0a76cf4bfbbc993fb"
    ap-northeast-2:
      "AMALINUX": "ami-0d097db2fb6e0f05e"
    ap-northeast-1:
      "AMALINUX": "ami-0ff21806645c5e492"
    sa-east-1:
      "AMALINUX": "ami-0a1f49a762473adbd"
    ca-central-1:
      "AMALINUX": "ami-085edf38cedbea498"
    ap-southeast-1:
      "AMALINUX": "ami-048a01c78f7bae4aa"
    ap-southeast-2:
      "AMALINUX": "ami-03ed5bd63ba378bd8"
    eu-central-1:
      "AMALINUX": "ami-00aa4671cbf840d82"
    us-east-1:
      "AMALINUX": "ami-0b69ea66ff7391e80"
    us-east-2:
      "AMALINUX": "ami-00c03f7f7f2ec15c3"
    us-west-1:
      "AMALINUX": "ami-0245d318c6788de52"
    us-west-2:
      "AMALINUX": "ami-04b762b4289fba92b"
  EnvSize:
    SMALL:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    MEDIUM:
      "EC2": "t2.small"
      "DB": "db.t2.small"
    LARGE:
      "EC2": "t2.medium"
      "DB": "db.t2.medium"
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-028188d9b49b32a80 # Linux 1 AMI (Oct'19) in eu-west-1
      InstanceType: !FindInMap [EnvSize, !Ref EnvironmentSize, EC2]
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [EnvSize, !Ref EnvironmentSize, DB]
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterPassword: w0rdpr355
  S3:
    Type: AWS::S3::Bucket