# V02 Template, with portability & reuse
# V03 Template, using User Data
Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S, M, L)
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the Key Pair for the EC2 Instance
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true
Mappings:
  RegionMap:
    eu-north-1:
      "AMALINUX": "ami-6a1f9414"
      "AMALINUX2": "ami-1b2fa465"
      "WINDOWS": "ami-09812ee174a6cb377"
    ap-south-1:
      "AMALINUX": "ami-02913db388613c3e1"
      "AMALINUX2": "ami-0cb0e70f44e1a4bb5"
      "WINDOWS": "ami-0eee945deafa2287b"
    eu-west-3:
      "AMALINUX": "ami-0652eb0db9b20aeaf"
      "AMALINUX2": "ami-03b4b78aae82b30f1"
      "WINDOWS": "ami-098a3826be1ee7dbf"
    eu-west-2:
      "AMALINUX": "ami-04de2b60dd25fbb2e"
      "AMALINUX2": "ami-00a1270ce1e007c27"
      "WINDOWS": "ami-014b5342eb453afee"
    eu-west-1:
      "AMALINUX": "ami-028188d9b49b32a80"
      "AMALINUX2": "ami-0ce71448843cb18a1"
      "WINDOWS": "ami-011b5156c098025a0"
    ap-northeast-2:
      "AMALINUX": "ami-0e1e385b0a934254a"
      "AMALINUX2": "ami-0d097db2fb6e0f05e"
      "WINDOWS": "ami-069e7b1c1551c3349"
    ap-northeast-1:
      "AMALINUX": "ami-0ab3e16f9c414dee7"
      "AMALINUX2": "ami-0ff21806645c5e492"
      "WINDOWS": "ami-04b47b75a5897bac8"
    sa-east-1:
      "AMALINUX": "ami-0e2c2c29d8017dd99"
      "AMALINUX2": "ami-0a1f49a762473adbd"
      "WINDOWS": "ami-0ed0752f521439848"
    ca-central-1:
      "AMALINUX": "ami-04070f04f450607dc"
      "AMALINUX2": "ami-085edf38cedbea498"
      "WINDOWS": "ami-05fbbab1511f0f785"
    ap-southeast-1:
      "AMALINUX": "ami-05c859630889c79c8"
      "AMALINUX2": "ami-048a01c78f7bae4aa"
      "WINDOWS": "ami-06bfbc4807fa73e58"
    ap-southeast-2:
      "AMALINUX": "ami-07cc15c3ba6f8e287"
      "AMALINUX2": "ami-03ed5bd63ba378bd8"
      "WINDOWS": "ami-04486ce22dea44562"
    eu-central-1:
      "AMALINUX": "ami-010fae13a16763bb4"
      "AMALINUX2": "ami-00aa4671cbf840d82"
      "WINDOWS": "ami-0091012d8fbe033f5"
    us-east-1:
      "AMALINUX": "ami-00eb20669e0990cb4"
      "AMALINUX2": "ami-0b69ea66ff7391e80"
      "WINDOWS": "ami-0dbbd6f952e12feba"
    us-east-2:
      "AMALINUX": "ami-0c64dd618a49aeee8"
      "AMALINUX2": "ami-00c03f7f7f2ec15c3"
      "WINDOWS": "ami-04203dd87d4abd6f6"
    us-west-1:
      "AMALINUX": "ami-0bce08e823ed38bdd"
      "AMALINUX2": "ami-0245d318c6788de52"
      "WINDOWS": "ami-05f5b1fdbdbc92ec7"
    us-west-2:
      "AMALINUX": "ami-08d489468314a58df"
      "AMALINUX2": "ami-04b762b4289fba92b"
      "WINDOWS": "ami-0e65e5829cd5a9dcd"
  InstancesSize:
    SMALL:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    MEDIUM:
      "EC2": "t2.small"
      "DB": "db.t2.small"
    LARGE:
      "EC2": "t2.medium"
      "DB": "db.t2.medium"
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX]
      InstanceType: !FindInMap [InstancesSize, !Ref EnvironmentSize, EC2]
      KeyName: !Ref KeyPair
      UserData: 
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstancesSize, !Ref EnvironmentSize, DB]
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  S3:
    Type: AWS::S3::Bucket