# V02 Template, with portability & reuse
# V03 Template, using User Data
# V04 Template, using CFN Init (modifed packages versions to work with latest Wordpress) and CreationPolicy
# V05 Template, adding Deletion Policy
# V06 Template, using more instrinsic functions, such as !GetAZs, !Join, !Select, !Equals, !Not or !If
Parameters:
  SnapToRestore:
    Type: String
    Default: ""
    Description: Snap ID to restore DB from
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S, M, L)
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the Key Pair for the EC2 Instance
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true
Conditions:
  isLarge:
    !Equals [!Ref EnvironmentSize, "LARGE"]
  isntLarge:
    !Not [!Equals [!Ref EnvironmentSize, "LARGE"]]
  isRestore:
    !Not [!Equals [!Ref SnapToRestore, ""]]
Mappings:
  RegionMap:
    eu-north-1:
      "AMALINUX": "ami-6a1f9414"
      "AMALINUX2": "ami-1b2fa465"
      "WINDOWS": "ami-09812ee174a6cb377"
    ap-south-1:
      "AMALINUX": "ami-02913db388613c3e1"
      "AMALINUX2": "ami-0cb0e70f44e1a4bb5"
      "WINDOWS": "ami-0eee945deafa2287b"
    eu-west-3:
      "AMALINUX": "ami-0652eb0db9b20aeaf"
      "AMALINUX2": "ami-03b4b78aae82b30f1"
      "WINDOWS": "ami-098a3826be1ee7dbf"
    eu-west-2:
      "AMALINUX": "ami-04de2b60dd25fbb2e"
      "AMALINUX2": "ami-00a1270ce1e007c27"
      "WINDOWS": "ami-014b5342eb453afee"
    eu-west-1:
      "AMALINUX": "ami-028188d9b49b32a80"
      "AMALINUX2": "ami-0ce71448843cb18a1"
      "WINDOWS": "ami-011b5156c098025a0"
    ap-northeast-2:
      "AMALINUX": "ami-0e1e385b0a934254a"
      "AMALINUX2": "ami-0d097db2fb6e0f05e"
      "WINDOWS": "ami-069e7b1c1551c3349"
    ap-northeast-1:
      "AMALINUX": "ami-0ab3e16f9c414dee7"
      "AMALINUX2": "ami-0ff21806645c5e492"
      "WINDOWS": "ami-04b47b75a5897bac8"
    sa-east-1:
      "AMALINUX": "ami-0e2c2c29d8017dd99"
      "AMALINUX2": "ami-0a1f49a762473adbd"
      "WINDOWS": "ami-0ed0752f521439848"
    ca-central-1:
      "AMALINUX": "ami-04070f04f450607dc"
      "AMALINUX2": "ami-085edf38cedbea498"
      "WINDOWS": "ami-05fbbab1511f0f785"
    ap-southeast-1:
      "AMALINUX": "ami-05c859630889c79c8"
      "AMALINUX2": "ami-048a01c78f7bae4aa"
      "WINDOWS": "ami-06bfbc4807fa73e58"
    ap-southeast-2:
      "AMALINUX": "ami-07cc15c3ba6f8e287"
      "AMALINUX2": "ami-03ed5bd63ba378bd8"
      "WINDOWS": "ami-04486ce22dea44562"
    eu-central-1:
      "AMALINUX": "ami-010fae13a16763bb4"
      "AMALINUX2": "ami-00aa4671cbf840d82"
      "WINDOWS": "ami-0091012d8fbe033f5"
    us-east-1:
      "AMALINUX": "ami-00eb20669e0990cb4"
      "AMALINUX2": "ami-0b69ea66ff7391e80"
      "WINDOWS": "ami-0dbbd6f952e12feba"
    us-east-2:
      "AMALINUX": "ami-0c64dd618a49aeee8"
      "AMALINUX2": "ami-00c03f7f7f2ec15c3"
      "WINDOWS": "ami-04203dd87d4abd6f6"
    us-west-1:
      "AMALINUX": "ami-0bce08e823ed38bdd"
      "AMALINUX2": "ami-0245d318c6788de52"
      "WINDOWS": "ami-05f5b1fdbdbc92ec7"
    us-west-2:
      "AMALINUX": "ami-08d489468314a58df"
      "AMALINUX2": "ami-04b762b4289fba92b"
      "WINDOWS": "ami-0e65e5829cd5a9dcd"
  InstancesSize:
    SMALL:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    MEDIUM:
      "EC2": "t2.small"
      "DB": "db.t2.small"
    LARGE:
      "EC2": "t2.medium"
      "DB": "db.t2.medium"
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX]
      InstanceType: !FindInMap [InstancesSize, !Ref EnvironmentSize, EC2]
      KeyName: !Ref KeyPair
      UserData: 
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum -y update
            yum update -y aws-cfn-bootstrap # update CFN init to latest version
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
            yum -y update
            /opt/aws/bin/cfn-signal -e $ --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region} # this is necessary to send a signal back to CFN
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          wordpress:
            - "configure_cfn"
            - "install_wordpress"
            - "config_wordpress"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
            #/var/www/html/index2.html:
            #  content: !Ref TestString
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
        install_wordpress:
          packages:
            yum:
              httpd24: []
              php73: []
              mysql56-server: []
              php73-mysqlnd: []
          sources:
            /var/www/html: "http://wordpress.org/latest.tar.gz"
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
        config_wordpress:
          commands:
            01_clone_config:
              cwd: "/var/www/html/wordpress"
              test: "test ! -e /var/www/html/wordpress/wp-config.php"
              command: "cp wp-config-sample.php wp-config.php"
            02_inject_dbhost:
              cwd: "/var/www/html/wordpress"
              command: !If
                - isntLarge 
                - !Sub |
                  sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
                - !Sub |
                  sed -i 's/localhost/${DBAuroraCluster.Endpoint.Address}/g' wp-config.php
            03_inject_dbname:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            04_inject_dbuser:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            05_inject_dbpassword:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
            06_store_instance_ip:
              cwd: "/var/www/html/wordpress"
              command: "curl http://169.254.169.254/latest/meta-data/public-ipv4 > ip.address"
            07a_inject_IP_1: # this allows a restore & change of IP without causing WP errors.
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "define('WP_SITEURL', 'http://${!myip}/wordpress');" >> wp-config.php
            07b_inject_IP_2: # this allows a restore & change of IP without causing WP errors.
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "define('WP_HOME', 'http://${!myip}/wordpress');" >> wp-config.php
            08a_update_theme_1:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "update_option('siteurl','http://${!myip}/wordpress');" >> /var/www/html/wordpress/wp-content/themes/twentyseventeen/functions.php
            08a_update_theme_2:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "update_option('home','http://${!myip}/wordpress');" >> /var/www/html/wordpress/wp-content/themes/twentyseventeen/functions.php
    CreationPolicy:
      ResourceSignal: # if the signal is successful, the resource will be created successfully, if not it will fail
        Count: "1"
        Timeout: PT15M
  DB:
    Condition: isntLarge
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstancesSize, !Ref EnvironmentSize, DB]
      DBName: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseName]
      Engine: MySQL
      MasterUsername: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseUser]
      MasterUserPassword: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabasePassword]
      DBSnapshotIdentifier: !If [isRestore, !Ref SnapToRestore, !Ref "AWS::NoValue"]
    DeletionPolicy: Delete
  DBAuroraCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Condition: isLarge
    Properties:
      DatabaseName: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseName]
      Engine: aurora
      MasterUsername: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseUser]
      MasterUserPassword: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabasePassword]
      SnapshotIdentifier: !If [isRestore, !Ref SnapToRestore, !Ref "AWS::NoValue"]
  DBAurora:
    Type: AWS::RDS::DBInstance
    Condition: isLarge
    Properties:
      DBClusterIdentifier: !Ref DBAuroraCluster
      Engine: aurora
      DBInstanceClass: !FindInMap [InstancesSize, !Ref EnvironmentSize, DB]
  S3:
    Type: AWS::S3::Bucket
Outputs:
  wproot:
    Description: Access URL for wordpress
    Value: !Join ["", ["http://", !GetAtt EC2.PublicIp, "/wordpress"]]
  wpadmin:
    Description: Admin Login URL - if restoring from snap, always go to this URL first
    Value: !Join ["", ["http://", !GetAtt EC2.PublicIp, "/wordpress/wp-login.php"]]